// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/admin" | "/admin/events" | "/admin/events/[id]" | "/admin/events/new" | "/admin/gallery" | "/admin/gallery/new" | "/admin/home" | "/admin/leaders" | "/admin/login" | "/admin/settings" | "/admin/team" | "/admin/team/new" | "/contact" | "/events" | "/gallery" | "/leaders" | "/team"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/admin": {}
  "/admin/events": {}
  "/admin/events/[id]": { "id": string; }
  "/admin/events/new": {}
  "/admin/gallery": {}
  "/admin/gallery/new": {}
  "/admin/home": {}
  "/admin/leaders": {}
  "/admin/login": {}
  "/admin/settings": {}
  "/admin/team": {}
  "/admin/team/new": {}
  "/contact": {}
  "/events": {}
  "/gallery": {}
  "/leaders": {}
  "/team": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
